# Generated by Django 5.2.3 on 2025-08-14 01:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=25)),
                ('direccion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('A', 'Académico'), ('T', 'Técnico')], max_length=1)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='instituciones/logos/', verbose_name='Logo institucional')),
                ('whatsapp_phone', models.CharField(blank=True, help_text='Número remitente con prefijo país, ej. +5068XXXXXXX', max_length=20, verbose_name='WhatsApp emisor (E.164)')),
                ('whatsapp_token', models.CharField(blank=True, max_length=255, verbose_name='Token API WhatsApp')),
                ('whatsapp_from_id', models.CharField(blank=True, help_text='ID del teléfono o phone_number_id según proveedor', max_length=50, verbose_name='WhatsApp From (ID/phone)')),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='1° Apellido')),
                ('second_last_name', models.CharField(blank=True, max_length=50, verbose_name='2° Apellido')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.PositiveSmallIntegerField(choices=[(1, 'Administrador'), (2, 'Docente'), (3, 'Administrativo')])),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='core.institucion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'institucion')},
            },
        ),
    ]
