# Generated by Django 5.2.3 on 2026-02-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_solicitud_whatsapp_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudregistro',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='solicitudes/comprobantes/', verbose_name='Comprobante de pago'),
        ),
    ]
