# Generated by Django 5.2.3 on 2026-03-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_solicitud_pago_config_aprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tiempo_cierre_sesion_min',
            field=models.PositiveSmallIntegerField(choices=[(5, '5 minutos'), (10, '10 minutos'), (15, '15 minutos'), (30, '30 minutos')], default=15, help_text='Tiempo de inactividad antes de cerrar sesión automáticamente.', verbose_name='Tiempo de cierre automático de sesión (minutos)'),
        ),
    ]
