# Generated by Django 5.2.3 on 2025-08-26 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subareainstitucion',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='subareainstitucion',
            name='subarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.subarea', verbose_name='Subárea'),
        ),
        migrations.AddField(
            model_name='subgrupo',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subgrupos', to='catalogos.seccion', verbose_name='Sección'),
        ),
        migrations.AlterUniqueTogether(
            name='seccion',
            unique_together={('nivel', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='subarea',
            unique_together={('nombre', 'especialidad')},
        ),
        migrations.AlterUniqueTogether(
            name='subareainstitucion',
            unique_together={('institucion', 'subarea')},
        ),
        migrations.AlterUniqueTogether(
            name='subgrupo',
            unique_together={('seccion', 'letra')},
        ),
    ]
