# Generated by Django 5.2.3 on 2025-08-14 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número de sección')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secciones_globales', to='catalogos.nivel', verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Sección (Global)',
                'verbose_name_plural': 'Secciones (Global)',
                'ordering': ('nivel__numero', 'numero'),
                'unique_together': {('nivel', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=2, verbose_name='Letra de subgrupo')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subgrupos', to='catalogos.seccion', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Subgrupo (Global)',
                'verbose_name_plural': 'Subgrupos (Global)',
                'ordering': ('seccion__nivel__numero', 'seccion__numero', 'letra'),
                'unique_together': {('seccion', 'letra')},
            },
        ),
    ]
