# Generated by Django 5.2.3 on 2025-06-25 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institucion'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='canton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.canton', verbose_name='Cantón'),
        ),
        migrations.AddField(
            model_name='clase',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.materia'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institucion'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institucion'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='profesores', through='catalogos.Clase', to='catalogos.materia'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.profesor'),
        ),
        migrations.AddField(
            model_name='canton',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institucion'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.nivel'),
        ),
        migrations.AddField(
            model_name='subarea',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.especialidad'),
        ),
        migrations.AddField(
            model_name='materia',
            name='subarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.subarea'),
        ),
        migrations.AddField(
            model_name='subgrupo',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institucion'),
        ),
        migrations.AddField(
            model_name='subgrupo',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subgrupos', to='catalogos.seccion'),
        ),
        migrations.AddField(
            model_name='clase',
            name='subgrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.subgrupo'),
        ),
        migrations.AlterUniqueTogether(
            name='seccion',
            unique_together={('nivel', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='subarea',
            unique_together={('especialidad', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('nombre', 'subarea', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='subgrupo',
            unique_together={('seccion', 'letra')},
        ),
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together={('materia', 'subgrupo', 'periodo')},
        ),
    ]
