# Generated by Django 5.2.3 on 2025-08-26 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAreaInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True, verbose_name='Subárea activa para esta institución')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion', verbose_name='Institución')),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.subarea', verbose_name='Subárea')),
            ],
            options={
                'verbose_name': 'Subárea por institución',
                'verbose_name_plural': 'Subáreas por institución',
                'ordering': ('subarea__nombre',),
                'unique_together': {('institucion', 'subarea')},
            },
        ),
    ]

