# Generated by Django 5.2.3 on 2025-07-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canton',
            options={'ordering': ('nombre',), 'verbose_name': 'Cantón', 'verbose_name_plural': 'Cantones'},
        ),
        migrations.AlterModelOptions(
            name='distrito',
            options={'ordering': ('nombre',), 'verbose_name': 'Distrito', 'verbose_name_plural': 'Distritos'},
        ),
    ]
