# Generated by Django 5.2.3 on 2025-08-01 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_canton_options_alter_distrito_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadocivil',
            options={'ordering': ('descripcion',), 'verbose_name': 'Estado civil', 'verbose_name_plural': 'Estados civiles'},
        ),
        migrations.AlterModelOptions(
            name='parentesco',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipoidentificacion',
            options={},
        ),
        migrations.RenameField(
            model_name='estadocivil',
            old_name='estado',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='parentesco',
            old_name='parentezco',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='adecuacion',
            name='descripcion',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.modalidad'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='nacionalidad',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
