# Generated by Django 5.2.3 on 2025-11-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursolectivo',
            name='matricular',
            field=models.BooleanField(default=False, help_text='Curso lectivo para el que se están recibiendo matrículas. Solo uno puede estar activo para matrícula.', verbose_name='Matricular en este curso'),
        ),
        migrations.AlterField(
            model_name='cursolectivo',
            name='activo',
            field=models.BooleanField(default=False, help_text='Curso lectivo en ejecución actual. Solo uno puede estar activo.', verbose_name='Curso activo'),
        ),
    ]
