# Generated by Django 5.2.3 on 2025-08-01 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_alter_estadocivil_options_alter_parentesco_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subarea',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subarea',
            name='es_academica',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.especialidad'),
        ),
        migrations.AlterUniqueTogether(
            name='subarea',
            unique_together={('nombre', 'especialidad')},
        ),
    ]
