# Generated by Django 5.2.3 on 2026-02-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_remove_seccion_tipo_estudiante_remove_subgrupo_tipo_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursolectivo',
            name='anio',
            field=models.PositiveIntegerField(choices=[(2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031)], verbose_name='Año'),
        ),
    ]
