# Generated by Django 5.2.3 on 2026-02-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0004_becacomedor_add_tiquete_permission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registroalmuerzo',
            new_name='comedor_reg_institu_ece583_idx',
            old_name='comedor_reg_institu_818b72_idx',
        ),
        migrations.RenameIndex(
            model_name='registroalmuerzo',
            new_name='comedor_reg_institu_588a4a_idx',
            old_name='comedor_reg_institu_est_fh_idx',
        ),
        migrations.RenameIndex(
            model_name='registroalmuerzotiquete',
            new_name='comedor_reg_institu_74ce29_idx',
            old_name='comedor_rat_institu_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='registroalmuerzotiquete',
            new_name='comedor_reg_tiquete_c6a10a_idx',
            old_name='comedor_rat_tiquete_fh_idx',
        ),
    ]
