# Generated by Django 5.2.3 on 2026-03-07 19:04

import django.db.models.deletion
from django.db import migrations, models


def poblar_centros_principales(apps, schema_editor):
    Institucion = apps.get_model("core", "Institucion")
    Profesor = apps.get_model("config_institucional", "Profesor")
    CentroTrabajo = apps.get_model("evaluaciones", "CentroTrabajo")
    DocenteAsignacion = apps.get_model("evaluaciones", "DocenteAsignacion")

    instituciones_general_ids = set(
        Institucion.objects.filter(es_institucion_general=True).values_list("id", flat=True)
    )
    if not instituciones_general_ids:
        return

    centros_por_docente = {}
    profesores = Profesor.objects.filter(institucion_id__in=instituciones_general_ids).only("id", "institucion_id")
    for prof in profesores:
        centro, _ = CentroTrabajo.objects.get_or_create(
            docente_id=prof.id,
            institucion_id=prof.institucion_id,
            nombre="Centro principal",
            defaults={"activo": True},
        )
        centros_por_docente[prof.id] = centro.id

    if not centros_por_docente:
        return

    for docente_id, centro_id in centros_por_docente.items():
        DocenteAsignacion.objects.filter(
            docente_id=docente_id,
            centro_trabajo_id__isnull=True,
        ).update(centro_trabajo_id=centro_id)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('config_institucional', '0006_profesor_max_asignaciones_override'),
        ('core', '0007_solicitud_pago_config_aprobacion'),
        ('evaluaciones', '0004_remove_docenteasignacion_eval_da_cl_docente_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del centro de trabajo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='centros_trabajo/', verbose_name='Logo del centro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_trabajo', to='config_institucional.profesor', verbose_name='Docente')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_trabajo', to='core.institucion', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Centro de trabajo',
                'verbose_name_plural': 'Centros de trabajo',
                'db_table': 'eval_centro_trabajo',
                'ordering': ('nombre',),
                'unique_together': {('docente', 'institucion', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='docenteasignacion',
            name='centro_trabajo',
            field=models.ForeignKey(blank=True, help_text='Obligatorio en Institución General para separar colegios/sedes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='evaluaciones.centrotrabajo', verbose_name='Centro de trabajo'),
        ),
        migrations.RunPython(poblar_centros_principales, migrations.RunPython.noop),
    ]
