# Generated by Django 5.2.3 on 2026-03-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_centrotrabajo_docenteasignacion_centro_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='docenteasignacion',
            name='nombre_corto',
            field=models.CharField(blank=True, default='', help_text='Alias opcional para mostrar la asignación en el horario (ej. MAT, ESP, PROG).', max_length=20, verbose_name='Nombre corto'),
        ),
    ]
