# Generated by Django 5.2.3 on 2025-06-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(default='Actual', max_length=20, verbose_name='Periodo lectivo')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ('subgrupo__seccion__nivel__numero', 'subgrupo__seccion__numero', 'subgrupo__letra', 'materia__nombre'),
            },
        ),
        migrations.CreateModel(
            name='NivelInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Nivel por institución',
                'verbose_name_plural': 'Niveles por institución',
                'ordering': ('nivel__numero',),
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20, unique=True, verbose_name='Identificación')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, verbose_name='Segundo apellido')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ('primer_apellido', 'segundo_apellido', 'nombres'),
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número de sección')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ('nivel__numero', 'numero'),
            },
        ),
        migrations.CreateModel(
            name='SubAreaInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Subárea por institución',
                'verbose_name_plural': 'Subáreas por institución',
                'ordering': ('subarea__especialidad__modalidad__nombre', 'subarea__nombre'),
            },
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=2, verbose_name='Letra de subgrupo')),
            ],
            options={
                'verbose_name': 'Subgrupo',
                'verbose_name_plural': 'Subgrupos',
                'ordering': ('seccion__nivel__numero', 'seccion__numero', 'letra'),
            },
        ),
    ]
