# Generated by Django 5.2.3 on 2025-08-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(default='Actual', max_length=20, verbose_name='Periodo lectivo')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ('subgrupo__seccion__nivel__numero', 'subgrupo__seccion__numero', 'subgrupo__letra', 'subarea__nombre'),
            },
        ),
        migrations.CreateModel(
            name='CursoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], verbose_name='Año')),
                ('nombre', models.CharField(help_text='Ej: Curso Lectivo 2025', max_length=50, verbose_name='Nombre del curso')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio del año lectivo')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin del año lectivo')),
                ('activo', models.BooleanField(default=True, verbose_name='Curso activo')),
            ],
            options={
                'verbose_name': 'Curso Lectivo',
                'verbose_name_plural': 'Cursos Lectivos',
                'ordering': ('-anio',),
            },
        ),
        migrations.CreateModel(
            name='NivelInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Nivel por institución',
                'verbose_name_plural': 'Niveles por institución',
                'ordering': ('nivel__numero',),
            },
        ),
        migrations.CreateModel(
            name='PeriodoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del período')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
            ],
            options={
                'verbose_name': 'Período Lectivo',
                'verbose_name_plural': 'Períodos Lectivos',
                'ordering': ('curso_lectivo__anio', 'fecha_inicio'),
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Identificación')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Docentes',
                'ordering': ('usuario__last_name', 'usuario__second_last_name', 'usuario__first_name'),
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número de sección')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ('nivel__numero', 'numero'),
            },
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=2, verbose_name='Letra de subgrupo')),
            ],
            options={
                'verbose_name': 'Subgrupo',
                'verbose_name_plural': 'Subgrupos',
                'ordering': ('seccion__nivel__numero', 'seccion__numero', 'letra'),
            },
        ),
    ]
