# Generated by Django 5.2.3 on 2025-08-14 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('config_institucional', '0002_initial'),
        ('core', '0002_alter_institucion_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadCursoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True, verbose_name='Especialidad activa para este curso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('curso_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_institucional.cursolectivo', verbose_name='Curso Lectivo')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.especialidad', verbose_name='Especialidad')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Especialidad por curso lectivo',
                'verbose_name_plural': 'Especialidades por curso lectivo',
                'ordering': ('curso_lectivo__anio', 'especialidad__nombre'),
                'unique_together': {('institucion', 'curso_lectivo', 'especialidad')},
            },
        ),
    ]
