# Generated by Django 5.2.3 on 2025-07-31 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_institucional', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion')),
            ],
            options={
                'ordering': ('institucion', 'anio', 'fecha_inicio'),
                'unique_together': {('institucion', 'anio', 'nombre')},
            },
        ),
    ]
