# Generated by Django 5.2.3 on 2025-08-27 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_institucional', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgrupocursolectivo',
            name='especialidad_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config_institucional.especialidadcursolectivo', verbose_name='Especialidad (solo 10°, 11°, 12°)'),
        ),
    ]
