# Generated by Django 5.2.3 on 2025-08-19 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_institucional', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidadcursolectivo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='especialidadcursolectivo',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='seccioncursolectivo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='seccioncursolectivo',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='subgrupocursolectivo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='subgrupocursolectivo',
            name='fecha_modificacion',
        ),
    ]
