# Generated by Django 5.2.3 on 2025-08-14 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_institucional', '0003_especialidadcursolectivo'),
        ('core', '0002_alter_institucion_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionCursoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True, verbose_name='Sección activa para este curso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('curso_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_institucional.cursolectivo', verbose_name='Curso Lectivo')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion', verbose_name='Institución')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config_institucional.seccion', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Sección por Curso Lectivo',
                'verbose_name_plural': 'Secciones por Curso Lectivo',
                'ordering': ('curso_lectivo__anio', 'seccion__nivel__numero', 'seccion__numero'),
                'unique_together': {('institucion', 'curso_lectivo', 'seccion')},
            },
        ),
        migrations.CreateModel(
            name='SubgrupoCursoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True, verbose_name='Subgrupo activo para este curso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('curso_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_institucional.cursolectivo', verbose_name='Curso Lectivo')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion', verbose_name='Institución')),
                ('subgrupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config_institucional.subgrupo', verbose_name='Subgrupo')),
            ],
            options={
                'verbose_name': 'Subgrupo por Curso Lectivo',
                'verbose_name_plural': 'Subgrupos por Curso Lectivo',
                'ordering': ('curso_lectivo__anio', 'subgrupo__seccion__nivel__numero', 'subgrupo__letra'),
                'unique_together': {('institucion', 'curso_lectivo', 'subgrupo')},
            },
        ),
    ]
