# Generated by Django 5.2.3 on 2025-08-14 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_seccion_subgrupo'),
        ('config_institucional', '0004_seccioncursolectivo_subgrupocursolectivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccioncursolectivo',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.seccion', verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='subgrupocursolectivo',
            name='subgrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.subgrupo', verbose_name='Subgrupo'),
        ),
    ]
