# Generated by Django 5.2.3 on 2025-10-25 01:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_initial'),
        ('config_institucional', '0003_subgrupocursolectivo_especialidad_curso'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionGrupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('total_estudiantes', models.PositiveIntegerField(verbose_name='Total de Estudiantes Asignados')),
                ('total_mujeres', models.PositiveIntegerField(verbose_name='Total Mujeres')),
                ('total_hombres', models.PositiveIntegerField(verbose_name='Total Hombres')),
                ('total_otros', models.PositiveIntegerField(verbose_name='Total Otros')),
                ('secciones_utilizadas', models.PositiveIntegerField(verbose_name='Secciones Utilizadas')),
                ('subgrupos_utilizados', models.PositiveIntegerField(verbose_name='Subgrupos Utilizados')),
                ('hermanos_agrupados', models.PositiveIntegerField(default=0, verbose_name='Hermanos Agrupados Juntos')),
                ('algoritmo_version', models.CharField(default='v1.0', max_length=20, verbose_name='Versión del Algoritmo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('curso_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.cursolectivo', verbose_name='Curso Lectivo')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion', verbose_name='Institución')),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.nivel', verbose_name='Nivel')),
                ('usuario_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó la asignación')),
            ],
            options={
                'verbose_name': 'Asignación de Grupos',
                'verbose_name_plural': 'Asignaciones de Grupos',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estudiante', models.CharField(choices=[('PR', 'Plan regular'), ('PN', 'Plan nacional')], default='PR', max_length=2, verbose_name='Tipo de estudiante')),
                ('identificacion', models.CharField(max_length=20, verbose_name='Identificación')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='1° Apellido')),
                ('segundo_apellido', models.CharField(max_length=50, verbose_name='2° Apellido')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.CharField(max_length=100, verbose_name='Correo electrónico')),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_casa', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_exacta', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estudiantes/fotos/%Y/%m/', verbose_name='Foto')),
                ('ed_religiosa', models.BooleanField(default=False, verbose_name='Recibe Ed. Religiosa')),
                ('rige_poliza', models.DateField(blank=True, null=True, verbose_name='Rige Póliza')),
                ('vence_poliza', models.DateField(blank=True, null=True, verbose_name='Vence Póliza')),
                ('presenta_enfermedad', models.BooleanField(blank=True, null=True, verbose_name='Presenta alguna enfermedad')),
                ('detalle_enfermedad', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la(s) enfermedad(es)')),
                ('autoriza_derecho_imagen', models.BooleanField(default=False, verbose_name='Autoriza derecho de imagen')),
                ('numero_poliza', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de póliza')),
                ('medicamento_consume', models.TextField(blank=True, null=True, verbose_name='Medicamentos que consume')),
                ('posee_carnet_conapdis', models.BooleanField(default=False, verbose_name='Posee carnet de CONAPDIS')),
                ('posee_valvula_drenaje_lcr', models.BooleanField(default=False, verbose_name='Posee válvula de drenaje LCR')),
                ('usa_apoyo', models.BooleanField(default=False, verbose_name='Usa algún tipo de apoyo')),
                ('apoyo_cual', models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Cuál apoyo?')),
                ('tipo_condicion_diagnosticada', models.CharField(blank=True, choices=[('EA', 'Espectro Autista'), ('SD', 'Síndrome de Down'), ('OT', 'Otro')], max_length=2, null=True, verbose_name='Tipo de condición diagnosticada')),
                ('tipo_condicion_otro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro (especifique condición)')),
                ('posee_control', models.BooleanField(default=False, verbose_name='Posee algún tipo de control')),
                ('control_cual', models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Cuál control?')),
                ('orden_alejamiento', models.BooleanField(blank=True, null=True, verbose_name='Existe persona con orden de alejamiento')),
                ('orden_alejamiento_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la persona con orden')),
                ('adecuacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.adecuacion')),
                ('canton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.canton')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.distrito')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.nacionalidad')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.provincia')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.sexo')),
                ('tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.tipoidentificacion')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ('primer_apellido', 'nombres'),
                'permissions': [('access_consulta_estudiante', 'Puede acceder a Consulta de Estudiante'), ('print_ficha_estudiante', 'Puede imprimir ficha del estudiante'), ('print_comprobante_matricula', 'Puede imprimir comprobante de matrícula'), ('access_asignacion_grupos', 'Puede acceder a Asignación de Grupos')],
            },
        ),
        migrations.CreateModel(
            name='EstudianteInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('trasladado', 'Trasladado'), ('retirado', 'Retirado'), ('graduado', 'Graduado')], default='activo', max_length=15, verbose_name='Estado')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituciones_estudiante', to='matricula.estudiante', verbose_name='Estudiante')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes_institucion', to='core.institucion', verbose_name='Institución')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró')),
            ],
            options={
                'verbose_name': 'Historial institucional del estudiante',
                'verbose_name_plural': 'Historiales institucionales de estudiantes',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='MatriculaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado'), ('promovido', 'Promovido'), ('repitente', 'Repitente')], default='activo', max_length=15)),
                ('curso_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.cursolectivo', verbose_name='Curso Lectivo')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config_institucional.especialidadcursolectivo', verbose_name='Especialidad del curso lectivo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_academicas', to='matricula.estudiante')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institucion', verbose_name='Institución')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.nivel')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.seccion', verbose_name='Sección')),
                ('subgrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.subgrupo', verbose_name='Subgrupo')),
            ],
            options={
                'verbose_name': 'Matrícula académica',
                'verbose_name_plural': 'Matrículas académicas',
                'permissions': [('manage_seccion_subgrupo_estado', 'Puede gestionar sección, subgrupo y estado de matrícula')],
            },
        ),
        migrations.CreateModel(
            name='PersonaContacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=20, verbose_name='Identificación')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='1° Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='2° Apellido')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('celular_avisos', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('correo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo')),
                ('lugar_trabajo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar de trabajo')),
                ('telefono_trabajo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono trabajo')),
                ('escolaridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.escolaridad')),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.estadocivil')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institucion')),
                ('ocupacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.ocupacion')),
                ('tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.tipoidentificacion', verbose_name='Tipo de identificación')),
            ],
            options={
                'verbose_name': 'Persona de contacto',
                'verbose_name_plural': 'Personas de contacto',
                'ordering': ('primer_apellido', 'nombres'),
            },
        ),
        migrations.CreateModel(
            name='EncargadoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convivencia', models.BooleanField(blank=True, verbose_name='Convive con el estudiante')),
                ('principal', models.BooleanField(default=False, verbose_name='Es encargado principal')),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.parentesco')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.estudiante')),
                ('persona_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.personacontacto')),
            ],
            options={
                'verbose_name': 'Encargado de estudiante',
                'verbose_name_plural': 'Encargados de estudiantes',
            },
        ),
        migrations.CreateModel(
            name='PlantillaImpresionMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título principal')),
                ('logo_mep', models.ImageField(upload_to='plantillas/logos_mep/', verbose_name='Logo MEP')),
                ('encabezado', models.TextField(help_text='Puedes usar variables como {{ institucion.nombre }}', verbose_name='Encabezado superior')),
                ('pie_pagina', models.TextField(help_text='Puedes usar variables como {{ institucion.nombre }}', verbose_name='Pie de página')),
                ('institucion', models.ForeignKey(help_text='Institución a la que pertenece esta plantilla', on_delete=django.db.models.deletion.CASCADE, to='core.institucion', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Plantilla de impresión de matrícula',
                'verbose_name_plural': 'Plantillas de impresión de matrícula',
            },
        ),
        migrations.AddConstraint(
            model_name='estudiante',
            constraint=models.UniqueConstraint(fields=('identificacion',), name='unique_estudiante_identificacion_global'),
        ),
        migrations.AddConstraint(
            model_name='estudianteinstitucion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activo')), fields=('estudiante',), name='unique_estudiante_activo_por_vez'),
        ),
        migrations.AddConstraint(
            model_name='matriculaacademica',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activo')), fields=('estudiante', 'curso_lectivo'), name='uniq_matricula_activa_por_anio'),
        ),
        migrations.AddConstraint(
            model_name='personacontacto',
            constraint=models.UniqueConstraint(fields=('institucion', 'identificacion'), name='unique_persona_contacto_por_institucion'),
        ),
        migrations.AddConstraint(
            model_name='encargadoestudiante',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('estudiante',), name='unique_principal_por_estudiante'),
        ),
        migrations.AlterUniqueTogether(
            name='encargadoestudiante',
            unique_together={('estudiante', 'persona_contacto', 'parentesco')},
        ),
        migrations.AlterUniqueTogether(
            name='plantillaimpresionmatricula',
            unique_together={('institucion',)},
        ),
    ]
