# Generated by Django 5.2.3 on 2025-08-19 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('config_institucional', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaImpresionMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título principal')),
                ('logo_mep', models.ImageField(upload_to='plantillas/logos_mep/', verbose_name='Logo MEP')),
                ('encabezado', models.TextField(help_text='Puedes usar variables como {{ institucion.nombre }}', verbose_name='Encabezado superior')),
                ('pie_pagina', models.TextField(help_text='Puedes usar variables como {{ institucion.nombre }}', verbose_name='Pie de página')),
            ],
            options={
                'verbose_name': 'Plantilla global de impresión de matrícula',
                'verbose_name_plural': 'Plantilla global de impresión de matrícula',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estudiante', models.CharField(choices=[('PR', 'Plan regular'), ('PN', 'Plan nacional')], default='PR', max_length=2, verbose_name='Tipo de estudiante')),
                ('identificacion', models.CharField(max_length=20, verbose_name='Identificación')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='1° Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, verbose_name='2° Apellido')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('telefono_casa', models.CharField(blank=True, max_length=20)),
                ('direccion_exacta', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, help_text='Foto del estudiante (formato: JPG, PNG. Máximo 2MB)', null=True, upload_to='estudiantes/fotos/%Y/%m/', verbose_name='Foto del estudiante')),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico MEP')),
                ('ed_religiosa', models.BooleanField(default=False, verbose_name='Recibe Ed. Religiosa')),
                ('rige_poliza', models.DateField(blank=True, null=True, verbose_name='Rige Póliza')),
                ('vence_poliza', models.DateField(blank=True, null=True, verbose_name='Vence Póliza')),
                ('presenta_enfermedad', models.BooleanField(default=False, verbose_name='Presenta alguna enfermedad')),
                ('detalle_enfermedad', models.CharField(blank=True, max_length=255, verbose_name='Nombre de la(s) enfermedad(es)')),
                ('autoriza_derecho_imagen', models.BooleanField(default=False, verbose_name='Autoriza derecho de imagen')),
                ('numero_poliza', models.CharField(blank=True, max_length=50, verbose_name='Número de póliza')),
                ('adecuacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.adecuacion')),
                ('canton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.canton')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.distrito')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institucion')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.nacionalidad')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.provincia')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.sexo')),
                ('tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.tipoidentificacion')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ('primer_apellido', 'nombres'),
            },
        ),
        migrations.CreateModel(
            name='EncargadoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convivencia', models.BooleanField(blank=True, verbose_name='Convive con el estudiante')),
                ('principal', models.BooleanField(default=False, verbose_name='Es encargado principal')),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.parentesco')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.estudiante')),
            ],
            options={
                'verbose_name': 'Encargado de estudiante',
                'verbose_name_plural': 'Encargados de estudiantes',
            },
        ),
        migrations.CreateModel(
            name='PersonaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20, verbose_name='Identificación')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='1° Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, verbose_name='2° Apellido')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('celular_avisos', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('correo', models.CharField(blank=True, max_length=100, verbose_name='Correo')),
                ('lugar_trabajo', models.CharField(blank=True, max_length=100, verbose_name='Lugar de trabajo')),
                ('telefono_trabajo', models.CharField(blank=True, max_length=20, verbose_name='Teléfono trabajo')),
                ('escolaridad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.escolaridad')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.estadocivil')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institucion')),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.ocupacion')),
            ],
            options={
                'verbose_name': 'Persona de contacto',
                'verbose_name_plural': 'Personas de contacto',
                'ordering': ('primer_apellido', 'nombres'),
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='contactos',
            field=models.ManyToManyField(related_name='estudiantes', through='matricula.EncargadoEstudiante', to='matricula.personacontacto'),
        ),
        migrations.AddField(
            model_name='encargadoestudiante',
            name='persona_contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.personacontacto'),
        ),
        migrations.CreateModel(
            name='MatriculaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(blank=True, choices=[('activo', 'Activo'), ('retirado', 'Retirado'), ('promovido', 'Promovido'), ('repitente', 'Repitente')], default='activo', max_length=15, null=True)),
                ('curso_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.cursolectivo', verbose_name='Curso Lectivo')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.especialidad')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_academicas', to='matricula.estudiante')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.nivel')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config_institucional.seccion', verbose_name='Sección')),
                ('subgrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config_institucional.subgrupo', verbose_name='Subgrupo')),
            ],
            options={
                'verbose_name': 'Matrícula académica',
                'verbose_name_plural': 'Matrículas académicas',
                'unique_together': {('estudiante', 'nivel', 'seccion', 'subgrupo', 'curso_lectivo')},
            },
        ),
        migrations.AddConstraint(
            model_name='personacontacto',
            constraint=models.UniqueConstraint(fields=('institucion', 'identificacion'), name='unique_persona_contacto_por_institucion'),
        ),
        migrations.AddConstraint(
            model_name='estudiante',
            constraint=models.UniqueConstraint(fields=('institucion', 'identificacion'), name='unique_estudiante_por_institucion'),
        ),
        migrations.AddConstraint(
            model_name='encargadoestudiante',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('estudiante',), name='unique_principal_por_estudiante'),
        ),
        migrations.AlterUniqueTogether(
            name='encargadoestudiante',
            unique_together={('estudiante', 'persona_contacto', 'parentesco')},
        ),
    ]
