# Generated by Django 5.2.3 on 2025-08-27 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_initial'),
        ('core', '0001_initial'),
        ('matricula', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionGrupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('total_estudiantes', models.PositiveIntegerField(verbose_name='Total de Estudiantes Asignados')),
                ('total_mujeres', models.PositiveIntegerField(verbose_name='Total Mujeres')),
                ('total_hombres', models.PositiveIntegerField(verbose_name='Total Hombres')),
                ('total_otros', models.PositiveIntegerField(verbose_name='Total Otros')),
                ('secciones_utilizadas', models.PositiveIntegerField(verbose_name='Secciones Utilizadas')),
                ('subgrupos_utilizados', models.PositiveIntegerField(verbose_name='Subgrupos Utilizados')),
                ('hermanos_agrupados', models.PositiveIntegerField(default=0, verbose_name='Hermanos Agrupados Juntos')),
                ('algoritmo_version', models.CharField(default='v1.0', max_length=20, verbose_name='Versión del Algoritmo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('curso_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.cursolectivo', verbose_name='Curso Lectivo')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion', verbose_name='Institución')),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.nivel', verbose_name='Nivel')),
                ('usuario_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó la asignación')),
            ],
            options={
                'verbose_name': 'Asignación de Grupos',
                'verbose_name_plural': 'Asignaciones de Grupos',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
