# Generated by Django 5.2.3 on 2025-08-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_matricula',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha registro'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numero_poliza',
            field=models.CharField(blank=True, max_length=50, verbose_name='Folio'),
        ),
    ]
