# Generated by Django 5.2.3 on 2025-11-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ('primer_apellido', 'nombres'), 'permissions': [('access_consulta_estudiante', 'Puede acceder a Consulta de Estudiante'), ('print_ficha_estudiante', 'Puede imprimir ficha del estudiante'), ('print_comprobante_matricula', 'Puede imprimir comprobante de matrícula'), ('access_asignacion_grupos', 'Puede acceder a Asignación de Grupos'), ('only_search_estudiante', 'Solo puede buscar estudiantes (no ve lista completa)')], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
    ]
