# Generated by Django 5.2.3 on 2025-07-06 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_canton_options_alter_distrito_options'),
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto del estudiante (formato: JPG, PNG. Máximo 2MB)', null=True, upload_to='estudiantes/fotos/%Y/%m/', verbose_name='Foto del estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='canton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.canton'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.distrito'),
        ),
    ]
