# Generated by Django 5.2.3 on 2025-06-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adecuacion',
        ),
        migrations.RemoveField(
            model_name='canton',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='distrito',
            name='canton',
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='Nacionalidad',
        ),
        migrations.DeleteModel(
            name='TipoIdentificacion',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
        migrations.DeleteModel(
            name='Canton',
        ),
        migrations.DeleteModel(
            name='Distrito',
        ),
    ]
