# Generated by Django 5.2.3 on 2025-08-21 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('matricula', '0002_alter_estudiante_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantillaimpresionmatricula',
            options={'verbose_name': 'Plantilla de impresión de matrícula', 'verbose_name_plural': 'Plantillas de impresión de matrícula'},
        ),
        migrations.AddField(
            model_name='plantillaimpresionmatricula',
            name='institucion',
            field=models.ForeignKey(blank=True, help_text='Institución a la que pertenece esta plantilla', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.institucion', verbose_name='Institución'),
        ),
        migrations.AlterUniqueTogether(
            name='plantillaimpresionmatricula',
            unique_together={('institucion',)},
        ),
    ]
