# Generated by Django 5.2.3 on 2025-11-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_alter_estudiante_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personacontacto',
            options={'ordering': ('primer_apellido', 'nombres'), 'permissions': [('only_search_personacontacto', 'Solo puede buscar personas de contacto (no ve lista completa)')], 'verbose_name': 'Persona de contacto', 'verbose_name_plural': 'Personas de contacto'},
        ),
    ]
