# Generated by Django 5.2.3 on 2025-08-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_estudiante_es_plan_nacional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='es_plan_nacional',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='medicamento_dosis',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='toma_medicamento',
        ),
    ]
