# Generated by Django 5.2.3 on 2025-07-24 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_canton_options_alter_distrito_options'),
        ('matricula', '0002_estudiante_foto_alter_estudiante_canton_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='adecuacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.adecuacion'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='autoriza_derecho_imagen',
            field=models.BooleanField(default=False, verbose_name='Autoriza derecho de imagen'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='correo',
            field=models.EmailField(blank=True, editable=False, max_length=100, null=True, verbose_name='Correo electrónico MEP'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='detalle_enfermedad',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre de la(s) enfermedad(es)'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ed_religiosa',
            field=models.BooleanField(default=False, verbose_name='Recibe Ed. Religiosa'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_matricula',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de matrícula'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='numero_poliza',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de Póliza'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='presenta_enfermedad',
            field=models.BooleanField(default=False, verbose_name='Presenta alguna enfermedad'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='recibe_afectividad_sexualidad',
            field=models.BooleanField(default=False, verbose_name='Recibe Afectividad y Sexualidad'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='rige_poliza',
            field=models.DateField(blank=True, null=True, verbose_name='Rige Póliza'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='vence_poliza',
            field=models.DateField(blank=True, null=True, verbose_name='Vence Póliza'),
        ),
        migrations.AlterField(
            model_name='encargadoestudiante',
            name='convivencia',
            field=models.BooleanField(blank=True, verbose_name='Convive con el estudiante'),
        ),
    ]
