# Generated by Django 5.2.3 on 2025-09-04 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0003_alter_estudiante_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ('primer_apellido', 'nombres'), 'permissions': [('access_consulta_estudiante', 'Puede acceder a Consulta de Estudiante'), ('print_ficha_estudiante', 'Puede imprimir ficha del estudiante'), ('print_comprobante_matricula', 'Puede imprimir comprobante de matrícula'), ('access_asignacion_grupos', 'Puede acceder a Asignación de Grupos')], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
    ]
