# Generated by Django 5.0.7 on 2025-08-20 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('matricula', '0003_alter_plantillaimpresionmatricula_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillaimpresionmatricula',
            name='institucion',
            field=models.ForeignKey(
                help_text='Institución a la que pertenece esta plantilla',
                on_delete=django.db.models.deletion.CASCADE,
                to='core.institucion',
                verbose_name='Institución'
            ),
        ),
    ]
