# Generated by Django 5.2.3 on 2025-12-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0003_alter_personacontacto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matriculaacademica',
            options={'permissions': [('manage_seccion_subgrupo_estado', 'Puede gestionar sección, subgrupo y estado de matrícula'), ('access_reporte_matricula', 'Puede acceder al reporte de matrícula académica')], 'verbose_name': 'Matrícula académica', 'verbose_name_plural': 'Matrículas académicas'},
        ),
    ]
