# Generated by Django 5.2.3 on 2025-07-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0003_estudiante_adecuacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico MEP'),
        ),
    ]
