# Generated by Django 5.2.3 on 2025-08-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0003_remove_estudiante_es_plan_nacional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='posee_carnet_conapdis',
            field=models.BooleanField(default=False, verbose_name='Posee carnet de CONAPDIS'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='posee_control',
            field=models.BooleanField(default=False, verbose_name='Posee algún tipo de control'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='posee_valvula_drenaje_lcr',
            field=models.BooleanField(default=False, verbose_name='Posee válvula de drenaje LCR'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='usa_apoyo',
            field=models.BooleanField(default=False, verbose_name='Usa algún tipo de apoyo'),
        ),
    ]
