# Generated by Django 5.2.3 on 2025-10-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0004_alter_estudiante_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matriculaacademica',
            options={'permissions': [('manage_seccion_subgrupo_estado', 'Puede gestionar sección, subgrupo y estado de matrícula')], 'verbose_name': 'Matrícula académica', 'verbose_name_plural': 'Matrículas académicas'},
        ),
    ]
