# Generated by Django 5.2.3 on 2025-07-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0004_alter_estudiante_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_matricula',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de matrícula'),
        ),
    ]
