# Generated by Django 5.2.3 on 2025-10-25 00:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_initial'),
        ('core', '0001_initial'),
        ('matricula', '0005_add_permission_manage_seccion_subgrupo_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('trasladado', 'Trasladado'), ('retirado', 'Retirado')], default='activo', max_length=15, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Historial institucional del estudiante',
                'verbose_name_plural': 'Historiales institucionales de estudiantes',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='estudiante',
            name='unique_estudiante_por_institucion',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='institucion',
            field=models.ForeignKey(blank=True, help_text='Campo obsoleto - usar EstudianteInstitucion', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.institucion'),
        ),
        migrations.AddConstraint(
            model_name='estudiante',
            constraint=models.UniqueConstraint(fields=('identificacion',), name='unique_estudiante_identificacion_global'),
        ),
        migrations.AddField(
            model_name='estudianteinstitucion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituciones_historial', to='matricula.estudiante', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='estudianteinstitucion',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes_historial', to='core.institucion', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='estudianteinstitucion',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró'),
        ),
        migrations.AddConstraint(
            model_name='estudianteinstitucion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activo')), fields=('estudiante',), name='unique_estudiante_institucion_activa'),
        ),
    ]
