# Generated by Django 5.2.3 on 2026-02-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0005_matriculaacademica_origen_carga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ('primer_apellido', 'nombres'), 'permissions': [('access_consulta_estudiante', 'Puede acceder a Consulta de Estudiante'), ('print_ficha_estudiante', 'Puede imprimir ficha del estudiante'), ('print_comprobante_matricula', 'Puede imprimir comprobante de matrícula'), ('print_pas_estudiante', 'Puede imprimir PAS del estudiante'), ('access_reporte_pas_seccion', 'Puede acceder a Reporte PAS por Sección'), ('access_asignacion_grupos', 'Puede acceder a Asignación de Grupos'), ('only_search_estudiante', 'Solo puede buscar estudiantes (no ve lista completa)')], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
    ]
