# Generated by Django 5.2.3 on 2025-10-25 00:47

from django.db import migrations
from django.utils import timezone


def migrar_estudiantes_a_institucion(apps, schema_editor):
    """
    Migra todos los estudiantes existentes a la nueva tabla EstudianteInstitucion.
    Cada estudiante que tenga una institución asignada en el campo 'institucion'
    se crea una entrada en EstudianteInstitucion con estado 'activo'.
    """
    Estudiante = apps.get_model('matricula', 'Estudiante')
    EstudianteInstitucion = apps.get_model('matricula', 'EstudianteInstitucion')
    
    estudiantes_con_institucion = Estudiante.objects.filter(institucion__isnull=False)
    
    total = estudiantes_con_institucion.count()
    print(f"\nMigrando {total} estudiantes al nuevo modelo EstudianteInstitucion...")
    
    migrados = 0
    for estudiante in estudiantes_con_institucion:
        # Crear la relación estudiante-institución
        EstudianteInstitucion.objects.get_or_create(
            estudiante=estudiante,
            institucion=estudiante.institucion,
            defaults={
                'estado': 'activo',
                'fecha_ingreso': timezone.now().date(),
                'observaciones': 'Migracion automatica desde campo institucion'
            }
        )
        migrados += 1
        if migrados % 100 == 0:
            print(f"  Migrados {migrados}/{total} estudiantes...")
    
    print(f"Migracion completada: {migrados} estudiantes migrados exitosamente.\n")


def revertir_migracion(apps, schema_editor):
    """
    Revierte la migración eliminando todas las entradas de EstudianteInstitucion
    """
    EstudianteInstitucion = apps.get_model('matricula', 'EstudianteInstitucion')
    total = EstudianteInstitucion.objects.count()
    print(f"\nRevirtiendo migracion: eliminando {total} registros de EstudianteInstitucion...")
    EstudianteInstitucion.objects.all().delete()
    print(f"Reversion completada.\n")


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0006_estudianteinstitucion_and_more'),
    ]

    operations = [
        migrations.RunPython(migrar_estudiantes_a_institucion, revertir_migracion),
    ]
