# Generated by Django 5.2.3 on 2026-04-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0006_alter_estudiante_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matriculaacademica',
            options={'permissions': [('manage_seccion_subgrupo_estado', 'Puede gestionar sección, subgrupo y estado de matrícula'), ('access_reporte_matricula', 'Puede acceder al reporte de matrícula académica'), ('access_reporte_estudiantes_encargados', 'Puede exportar reporte de estudiantes con encargados (Excel)')], 'verbose_name': 'Matrícula académica', 'verbose_name_plural': 'Matrículas académicas'},
        ),
    ]
