# Generated by Django 5.2.3 on 2025-08-23 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(db_index=True, max_length=20, verbose_name='Identificación estudiante')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('es_entrada', models.BooleanField(default=True)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institucion', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Registro de ingreso/salida',
                'verbose_name_plural': 'Registros de ingreso/salida',
                'ordering': ('-fecha_hora',),
                'constraints': [models.UniqueConstraint(fields=('institucion', 'identificacion', 'fecha_hora'), name='unique_registro_ingreso_por_institucion')],
            },
        ),
    ]
