# Generated by Django 5.2.3 on 2025-08-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(db_index=True, max_length=20, verbose_name='Identificación estudiante')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('es_entrada', models.BooleanField(default=True)),
                ('observacion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Registro de ingreso/salida',
                'verbose_name_plural': 'Registros de ingreso/salida',
                'ordering': ('-fecha_hora',),
            },
        ),
    ]
