# Generated by Django migration - Optimización de índices para asistencia

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Optimiza índices de asistencia_registro:
    - Elimina asis_reg_sesion_est_idx (redundante con UNIQUE uniq_registro_por_sesion_estudiante).
    - Añade asis_reg_sesion_est_estado_idx (sesion, estudiante, estado) para index-only scans
      en agregados por estudiante (P/T/AI/AJ).
    """

    dependencies = [
        ("libro_docente", "0003_patch_field_help_texts"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="asistenciaregistro",
            name="asis_reg_sesion_est_idx",
        ),
        migrations.AddIndex(
            model_name="asistenciaregistro",
            index=models.Index(
                fields=["sesion", "estudiante", "estado"],
                name="asis_reg_sesion_est_estado_idx",
            ),
        ),
    ]
