# Generated by Django 5.2.3 on 2026-02-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro_docente', '0014_lista_privada_docente_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadevaluacion',
            name='tipo_componente',
            field=models.CharField(choices=[('TAREA', 'Tarea'), ('COTIDIANO', 'Cotidiano'), ('PRUEBA', 'Prueba'), ('PROYECTO', 'Proyecto')], max_length=20, verbose_name='Tipo'),
        ),
    ]
