# Generated by Django 5.2.3 on 2026-03-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro_docente', '0016_asistenciasesion_minuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciasesion',
            name='minuta',
            field=models.CharField(blank=True, default='', help_text='Observación general del día (máximo 1000 caracteres).', max_length=1000, verbose_name='Minuta'),
        ),
    ]
