# Generated by Django 5.2.3 on 2026-03-07 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_remove_docenteasignacion_eval_da_cl_docente_idx_and_more'),
        ('libro_docente', '0017_alter_asistenciasesion_minuta'),
        ('matricula', '0006_alter_estudiante_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteAdecuacionNoSignificativaAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcas_adecuacion_no_significativa_libro_docente', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('docente_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_adecuacion_no_significativa', to='evaluaciones.docenteasignacion', verbose_name='Asignación docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adecuaciones_no_significativas_libro_docente', to='matricula.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Estudiante con adecuación no significativa por asignación',
                'verbose_name_plural': 'Estudiantes con adecuación no significativa por asignación',
                'db_table': 'libro_docente_estudiante_adecuacion_no_sig',
                'indexes': [models.Index(fields=['docente_asignacion', 'estudiante'], name='libro_doc_est_ad_no_sig_idx')],
                'constraints': [models.UniqueConstraint(fields=('docente_asignacion', 'estudiante'), name='uniq_libro_doc_est_adecuacion_no_sig')],
            },
        ),
    ]
