# Generated by Django 5.2.3 on 2026-03-08 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_institucional', '0006_profesor_max_asignaciones_override'),
        ('core', '0007_solicitud_pago_config_aprobacion'),
        ('evaluaciones', '0005_centrotrabajo_docenteasignacion_centro_trabajo'),
        ('libro_docente', '0018_estudianteadecuacionnosignificativaasignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDocenteConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_lecciones_dia', models.PositiveSmallIntegerField(choices=[(6, '6'), (8, '8'), (10, '10'), (12, '12'), (16, '16')], default=8, verbose_name='Máximo de lecciones por día')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horarios_docente', to='evaluaciones.centrotrabajo', verbose_name='Centro de trabajo')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_docente', to='config_institucional.profesor', verbose_name='Docente')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_docente', to='core.institucion', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Configuración de horario docente',
                'verbose_name_plural': 'Configuraciones de horario docente',
                'db_table': 'libro_docente_horario_config',
            },
        ),
        migrations.CreateModel(
            name='HorarioDocenteBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Día de semana')),
                ('leccion_numero', models.PositiveSmallIntegerField(verbose_name='Lección')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('docente_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_horario_docente', to='evaluaciones.docenteasignacion', verbose_name='Asignación docente')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='libro_docente.horariodocenteconfiguracion', verbose_name='Configuración de horario')),
            ],
            options={
                'verbose_name': 'Bloque de horario docente',
                'verbose_name_plural': 'Bloques de horario docente',
                'db_table': 'libro_docente_horario_bloque',
                'ordering': ('dia_semana', 'leccion_numero'),
            },
        ),
        migrations.AddConstraint(
            model_name='horariodocenteconfiguracion',
            constraint=models.UniqueConstraint(condition=models.Q(('centro_trabajo__isnull', False)), fields=('docente', 'centro_trabajo'), name='uniq_horario_docente_centro'),
        ),
        migrations.AddConstraint(
            model_name='horariodocenteconfiguracion',
            constraint=models.UniqueConstraint(condition=models.Q(('centro_trabajo__isnull', True)), fields=('docente',), name='uniq_horario_docente_sin_centro'),
        ),
        migrations.AddConstraint(
            model_name='horariodocentebloque',
            constraint=models.UniqueConstraint(fields=('configuracion', 'dia_semana', 'leccion_numero'), name='uniq_horario_docente_bloque'),
        ),
    ]
