# Generated by Django 5.2.3 on 2026-03-08 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro_docente', '0019_horariodocenteconfiguracion_horariodocentebloque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariodocenteconfiguracion',
            name='receso_despues_leccion',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Si se define, se mostrará una fila de receso entre esa lección y la siguiente.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(19)], verbose_name='Receso después de la lección'),
        ),
        migrations.AlterField(
            model_name='horariodocenteconfiguracion',
            name='max_lecciones_dia',
            field=models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Máximo de lecciones por día'),
        ),
    ]
