# Generated by Django 5.2.3 on 2026-03-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro_docente', '0020_horariodocenteconfiguracion_receso_despues_leccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariodocenteconfiguracion',
            name='receso_despues_leccion',
            field=models.CharField(blank=True, default='', help_text='Lista de lecciones separadas por coma. Ejemplo: 3,6 (receso entre 3-4 y 6-7).', max_length=120, verbose_name='Recesos después de lección'),
        ),
    ]
