# Generated by Django 5.2.3 on 2026-03-27 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_cursolectivo_anio'),
        ('config_institucional', '0006_profesor_max_asignaciones_override'),
        ('core', '0008_user_tiempo_cierre_sesion_min'),
        ('evaluaciones', '0006_docenteasignacion_nombre_corto'),
        ('libro_docente', '0021_alter_horariodocenteconfiguracion_receso_despues_leccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listaestudiantesdocente',
            name='uniq_libdoc_lista_doc_curso_seccion',
        ),
        migrations.RemoveConstraint(
            model_name='listaestudiantesdocente',
            name='uniq_libdoc_lista_doc_curso_subgrupo',
        ),
        migrations.AddField(
            model_name='listaestudiantesdocente',
            name='centro_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listas_estudiantes_docente', to='evaluaciones.centrotrabajo', verbose_name='Centro de trabajo'),
        ),
        migrations.AddConstraint(
            model_name='listaestudiantesdocente',
            constraint=models.UniqueConstraint(condition=models.Q(('centro_trabajo__isnull', True), ('seccion__isnull', False), ('subgrupo__isnull', True)), fields=('docente', 'institucion', 'curso_lectivo', 'seccion'), name='uniq_libdoc_lista_doc_inst_curso_seccion'),
        ),
        migrations.AddConstraint(
            model_name='listaestudiantesdocente',
            constraint=models.UniqueConstraint(condition=models.Q(('centro_trabajo__isnull', True), ('subgrupo__isnull', False)), fields=('docente', 'institucion', 'curso_lectivo', 'subgrupo'), name='uniq_libdoc_lista_doc_inst_curso_subgrupo'),
        ),
        migrations.AddConstraint(
            model_name='listaestudiantesdocente',
            constraint=models.UniqueConstraint(condition=models.Q(('centro_trabajo__isnull', False), ('seccion__isnull', False), ('subgrupo__isnull', True)), fields=('docente', 'institucion', 'curso_lectivo', 'centro_trabajo', 'seccion'), name='uniq_libdoc_lista_doc_inst_curso_ctr_seccion'),
        ),
        migrations.AddConstraint(
            model_name='listaestudiantesdocente',
            constraint=models.UniqueConstraint(condition=models.Q(('centro_trabajo__isnull', False), ('subgrupo__isnull', False)), fields=('docente', 'institucion', 'curso_lectivo', 'centro_trabajo', 'subgrupo'), name='uniq_libdoc_lista_doc_inst_curso_ctr_subgrupo'),
        ),
    ]
